### ISSUE TITLE
Addition of derived measures

### ISSUE THREAD

**Issue by PragmaticPhil** [shaoziyang/xinabox-pxt-sw01#3]
Please add the following blocks:

1 - Dewpoint:
dewpoint(arg).  Arg is a drop-down with options Celsius and Degrees.
**dewpoint = temperature - ((100 - humidity)/5)**

2 - Altiitude:
altitude(arg).  Arg is a drop-down with options meters / feet
**altitude = ((pow((101325 / pressure(Pa), 1/5.257) - 1.0) * (temperature(C) + 273.15)) / 0.0065**

3 - Cloud base
cloudBase(arg).  Arg is a drop-down with options meters / feet
**cloudBase = ((((temperature - dew point) / 4.5) * 1000) + altitude**

**Comment by shaoziyang** [comment]
add Dewpoint
